apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notepad-plus-plus
  description: Notepad++ é um editor de texto e código-fonte gratuito e de código aberto para Windows.
  annotations:
    #backstage.io/techdocs-ref: url:https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/README.md
  tags:
    - editor
    - open-source
    - windows
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: application
  owner: guests
  lifecycle: production
  providesApis:
    - notepad-plus-plus-api
  consumesApis:
    - markdown-api
  dependsOn:
    - component:default/markdown-parser
    - resource:default/windows-os
