apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notepad-plus-plus
  description: Notepad++ é um editor de texto e código-fonte gratuito e de código aberto para Windows.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/gustavoguanabara/projeto-site.git
  tags:
    - editor
    - open-source
    - windows
  links:
    - url: https://notepad-plus-plus.org/
      title: Official Website
      icon: techdocs
    - url: https://notepad-plus-plus.org/downloads/
      title: Download Notepad
      icon: web
spec:
  type: application
  owner: guests
  lifecycle: production
  providesApis:
    - notepad-plus-plus-api
  consumesApis:
    - markdown-api
  dependsOn:
    - component:default/markdown-parser
    - resource:default/windows-os
