apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redmine
  description: Redmine é um aplicativo web flexível de gerenciamento de projetos.
  annotations:
    github.com/project-slug: redmine/redmine
    backstage.io/techdocs-ref: url:https://raw.githubusercontent.com/redmine/redmine/master/README.md
  tags:
    - gerenciamento-de-projetos
    - open-source
    - web
  links:
    - url: https://www.redmine.org/
      title: Official Website
      icon: techdocs
    - url: https://www.redmine.org/projects/redmine/wiki/Download
      title: Download Redmine
      icon: web

spec:
  type: application
  owner: guests
  lifecycle: production
  providesApis:
    - redmine-api
  consumesApis:
    - markdown-api
  dependsOn:
    - component:default/markdown-parser
    - resource:default/linux-os
